# Generated by Django 4.2.3 on 2023-11-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VODInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vod_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("viewers", models.IntegerField()),
                ("total_watch_time", models.IntegerField()),
            ],
            options={
                "db_table": "vodinfo",
            },
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsr", models.IntegerField()),
                ("use_tms", models.IntegerField(default=0)),
                (
                    "vod_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.vodinfo",
                    ),
                ),
            ],
            options={
                "db_table": "userlog",
            },
        ),
    ]
